### ISSUE TITLE
Reverse 

### ISSUE THREAD

**Issue by GreencapGonzo** [kumekay/handbrakerscript#1]
I would like a program to reverse this. as in take mp4 and convert it to motion jpeg. My tv has a thing where you plug a memory stick in the back to watch movies and all of mine are in MP4. It only supports motion jpg. can this help me (and if not can you patch a new program to do so)

**Comment by kumekay** [comment]
Handbrake is not right tool in this case. You can use bare ffmpeg:
`ffmpeg -i input.mp4 -c:v mjpeg -q:v 3 -an output.avi`

**Comment by GreencapGonzo** [comment]
Just to be shure this is in the comand line yes?

**Comment by kumekay** [comment]
Yes, and you have to install ffmpeg https://ffmpeg.org/download.html

**Comment by GreencapGonzo** [comment]
Thanks mate!
